package com.github.deckyfx.dbsession.dao;

import java.util.Map;

import com.github.deckyfx.greendao.AbstractDao;
import com.github.deckyfx.greendao.AbstractDaoSession;
import com.github.deckyfx.greendao.database.Database;
import com.github.deckyfx.greendao.identityscope.IdentityScopeType;
import com.github.deckyfx.greendao.internal.DaoConfig;

import com.github.deckyfx.dbsession.dao.DbSession;

import com.github.deckyfx.dbsession.dao.DbSessionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see com.github.deckyfx.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbSessionDaoConfig;

    private final DbSessionDao dbSessionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbSessionDaoConfig = daoConfigMap.get(DbSessionDao.class).clone();
        dbSessionDaoConfig.initIdentityScope(type);

        dbSessionDao = new DbSessionDao(dbSessionDaoConfig, this);

        registerDao(DbSession.class, dbSessionDao);
    }
    
    public void clear() {
        dbSessionDaoConfig.clearIdentityScope();
    }

    public DbSessionDao getDbSessionDao() {
        return dbSessionDao;
    }

}
